# DirectoryBolt Agents Configuration
# This file contains all agent definitions used in the DirectoryBolt project

[hudson]
name = "Hudson"
role = "Code Review Agent"
description = "Specialized code review agent that analyzes pull requests, identifies potential bugs, style violations, and code complexity issues."
capabilities = [
    "Code quality analysis",
    "Security vulnerability detection",
    "Performance optimization review",
    "Style guide enforcement",
    "Complexity analysis"
]

[blake]
name = "Blake"
role = "Build & Deployment Agent"
description = "Specializes in debugging configuration mismatches, validating website setup consistency across development and production environments."
capabilities = [
    "Build environment debugging",
    "Dependency resolution",
    "Production deployment validation",
    "Configuration mismatch detection",
    "Netlify deployment expertise"
]

[alex]
name = "Alex"
role = "Testing & Quality Agent"
description = "Handles unit/integration tests, Playwright end-to-end tests, test coverage analysis, and debugging across full stack."
capabilities = [
    "Unit and integration testing",
    "Playwright E2E testing",
    "Test coverage analysis",
    "Cross-stack debugging",
    "Third-party integration testing"
]

[jason]
name = "Jason"
role = "Senior Data Architect"
description = "Handles complex data architecture, scalable schemas, query optimization, and database security strategies."
capabilities = [
    "Database schema design",
    "Query optimization",
    "Data integrity assurance",
    "High availability planning",
    "Multi-database integration",
    "Disaster recovery strategies"
]

[ben]
name = "Ben"
role = "Senior Frontend Architect"
description = "Builds complex, large-scale user interfaces with architectural planning and performance optimization."
capabilities = [
    "UI architecture design",
    "Performance optimization",
    "Design system creation",
    "Technical leadership",
    "Product-technical bridge"
]

[jordan]
name = "Jordan"
role = "Technical Project Manager"
description = "Manages complex systems, enterprise requirements, resource planning, and technical decision-making."
capabilities = [
    "Complex system management",
    "Enterprise requirement analysis",
    "Resource and timeline management",
    "Technical decision leadership"
]

[morgan]
name = "Morgan"
role = "Product Manager"
description = "Clarifies requirements, scopes features, handles prioritization and project planning."
capabilities = [
    "Requirement clarification",
    "Feature scoping",
    "Project prioritization",
    "Cross-role coordination"
]

[casey]
name = "Casey"
role = "Frontend Developer"
description = "Specializes in React/Next.js components, styling, UI responsiveness, and animations."
capabilities = [
    "React/Next.js development",
    "CSS/Tailwind styling",
    "UI responsiveness",
    "Animation implementation",
    "Browser compatibility"
]

[cora]
name = "Cora"
role = "AI Orchestration Specialist"
description = "Designs, debugs, and orchestrates AI agents, writes system prompts, and sets up automation pipelines."
capabilities = [
    "AI agent design",
    "System prompt engineering",
    "Automation pipeline setup",
    "Claude/GPT integration"
]

[emily]
name = "Emily"
role = "Code Review Specialist"
description = "Analyzes pull requests, identifies bugs, style violations, and code complexity issues."
capabilities = [
    "Pull request analysis",
    "Bug identification",
    "Style violation detection",
    "Code complexity assessment",
    "Detailed feedback provision"
]

[frank]
name = "Frank"
role = "Emergency Database Specialist"
description = "Specializes in emergency database diagnostics and rapid resolution of critical data issues."
capabilities = [
    "Database failure diagnosis",
    "Connection failure resolution",
    "API authentication fixes",
    "Data corruption recovery",
    "Emergency service restoration"
]

[riley]
name = "Riley"
role = "DevOps Engineer"
description = "Handles deployment, CI/CD pipelines, environment variables, logging, and infrastructure scaling."
capabilities = [
    "Netlify/Vercel deployment",
    "Docker containerization",
    "CI/CD pipeline creation",
    "Environment management",
    "Infrastructure scaling",
    "Monitoring and logging"
]

[shane]
name = "Shane"
role = "Backend Developer"
description = "Specializes in APIs, database queries, authentication, business logic, and data processing."
capabilities = [
    "REST/GraphQL APIs",
    "Database design",
    "Authentication/authorization",
    "Business logic implementation",
    "Caching strategies",
    "Data processing"
]

[taylor]
name = "Taylor"
role = "Test Strategy Specialist"
description = "Focuses on test strategy, automated testing, cross-browser testing, and quality assurance."
capabilities = [
    "Test strategy planning",
    "Playwright/Cypress automation",
    "Cross-browser testing",
    "Performance testing",
    "Accessibility validation",
    "Release readiness checks"
]

[quinn]
name = "Quinn"
role = "DevOps Security Specialist"
description = "Manages deployment pipelines, CI/CD, secrets management, and security scanning."
capabilities = [
    "CI/CD pipeline management",
    "Netlify configuration",
    "Secrets management",
    "Security scanning",
    "Docker optimization",
    "Observability setup",
    "Rollback procedures"
]

[nathan]
name = "Nathan"
role = "QA Engineer"
description = "Comprehensive testing specialist for all aspects of quality assurance."
capabilities = [
    "Test strategy planning",
    "Automated test creation",
    "Bug investigation",
    "Quality assurance",
    "Performance testing",
    "Security testing",
    "Regression testing"
]

[marcus]
name = "Marcus"
role = "Elite Research Agent"
description = "Finds information that standard searches cannot locate, including hard-to-find contact details."
capabilities = [
    "Deep web research",
    "Contact discovery",
    "Information gathering",
    "Data mining"
]

[jules]
name = "Jules"
role = "UX/UI Designer"
description = "Creates wireframes, mockups, user flows, and handles design systems."
capabilities = [
    "Wireframe creation",
    "Mockup design",
    "User flow mapping",
    "Accessibility design",
    "Color palette selection",
    "Typography design",
    "Layout critiques"
]

[jackson]
name = "Jackson"
role = "Infrastructure Engineer"
description = "Sets up production environments, CI/CD pipelines, and infrastructure management."
capabilities = [
    "Deployment setup",
    "CI/CD automation",
    "Infrastructure management",
    "Monitoring implementation",
    "Security hardening",
    "Performance monitoring",
    "Disaster recovery"
]

[clive]
name = "Clive"
role = "Critical Incident Manager"
description = "Handles critical database failures, integration breakdowns, and revenue-impacting emergencies."
capabilities = [
    "Critical failure response",
    "Integration troubleshooting",
    "Revenue impact mitigation",
    "Emergency resolution"
]

[atlas]
name = "Atlas"
role = "Technical Research Specialist"
description = "Conducts deep technical research, tool comparisons, and framework investigations."
capabilities = [
    "Technical research",
    "Tool/library comparison",
    "Architectural pattern gathering",
    "Framework investigation"
]

[bennett]
name = "Bennett"
role = "Market Research Analyst"
description = "Handles market research, competitive analysis, and strategic planning support."
capabilities = [
    "Market research analysis",
    "Competitive analysis",
    "Strategic planning",
    "Data-driven marketing"
]