version: "3.9"

services:
  orchestrator:
    build: .
    container_name: autobolt-orchestrator
    command: ["npm", "run", "dev:api"]
    ports:
      - "4000:4000"   # local machine → container port
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      PORT: 4000
      JOB_STALL_MINUTES: 10
    restart: unless-stopped
    healthcheck:                  # <--- Health check added here
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  worker1:
    build: .
    container_name: autobolt-worker1
    command: ["npm", "run", "dev:worker"]
    depends_on:
      - orchestrator
    environment:
      API_BASE: http://orchestrator:4000
      WORKER_ID: worker-1
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      HTTP_PROXY: ${HTTP_PROXY}
      TWO_CAPTCHA_KEY: ${TWO_CAPTCHA_KEY}
    restart: unless-stopped

  worker2:
    build: .
    container_name: autobolt-worker2
    command: ["npm", "run", "dev:worker"]
    depends_on:
      - orchestrator
    environment:
      API_BASE: http://orchestrator:4000
      WORKER_ID: worker-2
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      HTTP_PROXY: ${HTTP_PROXY}
      TWO_CAPTCHA_KEY: ${TWO_CAPTCHA_KEY}
    restart: unless-stopped
