[build]
  command = "npm run build"
  publish = ".next"

  [build.environment]
    NODE_VERSION = "20.18.1"
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
    NODE_OPTIONS = "--max-old-space-size=4096"
    NETLIFY_BUILD_DEBUG = "true"
    NEXT_DISABLE_ESLINT = "true"
    CI = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"
  BUILDING = "true"
  NETLIFY = "true"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  BUILDING = "true"
  NETLIFY = "true"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  BUILDING = "true"
  NETLIFY = "true"

[[headers]]
  for = "/api/ai/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "/api/ai/health"
  to = "/.netlify/functions/ai-health-check"
  status = 200
  force = true

[[redirects]]
  from = "/api/puppeteer/*"
  to = "/.netlify/functions/puppeteer-handler"
  status = 200
  force = true


[[redirects]]
  from = "/api/customer/validate"
  to = "/.netlify/functions/customer-validate"
  status = 200
  force = true

[[redirects]]
  from = "/api/extension/secure-validate"
  to = "/.netlify/functions/extension-secure-validate"
  status = 200
  force = true

# AutoBolt Secure Backend API Redirects
[[redirects]]
  from = "/api/healthz"
  to = "/.netlify/functions/healthz"
  status = 200
  force = true

[[redirects]]
  from = "/api/version"
  to = "/.netlify/functions/version"
  status = 200
  force = true

[[redirects]]
  from = "/api/autobolt-status"
  to = "/.netlify/functions/autobolt-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/jobs-next"
  to = "/.netlify/functions/jobs-next"
  status = 200
  force = true

[[redirects]]
  from = "/api/jobs-update"
  to = "/.netlify/functions/jobs-update"
  status = 200
  force = true

[[redirects]]
  from = "/api/jobs-complete"
  to = "/.netlify/functions/jobs-complete"
  status = 200
  force = true

[[redirects]]
  from = "/api/jobs-retry"
  to = "/.netlify/functions/jobs-retry"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[dev]
  # Next.js in this environment binds to port 3001; ensure Netlify Dev waits on that port
  targetPort = 3000

