[build]
  # Directory with Netlify Functions
  functions = "netlify/functions"
  
  # Build command for Next.js
  command = "npm run build"
  
  # Directory to publish for Next.js
  publish = ".next"

[build.environment]
  # Node.js version (Next.js 14 requires Node 18+)
  NODE_VERSION = "20"

[functions]
  # Use esbuild for faster cold starts
  node_bundler = "esbuild"

# CORS headers for Netlify Functions
[[headers]]
  # Apply to all function endpoints
  for = "/.netlify/functions/*"
  [headers.values]
    # Restrict CORS to specific domain for security
    Access-Control-Allow-Origin = "https://directorybolt.com"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    
# Security headers for HTML pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache control for static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects (examples)
# [[redirects]]
#   from = "/old-pricing"
#   to = "/pricing"
#   status = 301

# Environment-specific configuration
[context.production]
  # Production-specific settings
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  # Deploy preview settings
  [context.deploy-preview.environment]
    NODE_ENV = "staging"

[context.branch-deploy]
  # Branch deploy settings
  [context.branch-deploy.environment]
    NODE_ENV = "development"