[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  SUPABASE_URL = "https://yourapp.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY = "your_default_supabase_service_key"
  STRIPE_SECRET_KEY = "your_default_stripe_secret_key"
  API_URL = "https://api.yourdomain.com" # overridden in staging/dev if needed
  NODE_ENV = "production" # default

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas", "sharp", "playwright-chromium"]
  included_files = ["src/assets/**", "src/templates/**", "src/styles/**"]
  timeout = 300

[[plugins]]
  package = "@netlify/plugin-sitemap"

# ────────────────────────────────
# HEADERS
# ────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src https://*.stripe.com; connect-src 'self' https://api.yourdomain.com"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# ────────────────────────────────
# REDIRECTS
# ────────────────────────────────
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://yourdomain.com/*"
  to = "https://www.yourdomain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/customer-validate"
  to = "/.netlify/functions/customer-validate"
  status = 200

[[redirects]]
  from = "/api/jobs-update"
  to = "/.netlify/functions/jobs-update"
  status = 200

[[redirects]]
  from = "/api/jobs-next"
  to = "/.netlify/functions/jobs-next"
  status = 200

[[redirects]]
  from = "/api/jobs-retry"
  to = "/.netlify/functions/jobs-retry"
  status = 200

[[redirects]]
  from = "/api/jobs-complete"
  to = "/.netlify/functions/jobs-complete"
  status = 200

[[redirects]]
  from = "/api/health-supabase"
  to = "/.netlify/functions/health-supabase"
  status = 200

[[redirects]]
  from = "/api/healthz"
  to = "/.netlify/functions/healthz"
  status = 200

[[redirects]]
  from = "/api/version"
  to = "/.netlify/functions/version"
  status = 200

[[redirects]]
  from = "/old-checkout"
  to = "/.netlify/functions/create-checkout-session"
  status = 301

[[redirects]]
  from = "/old-health"
  to = "/.netlify/functions/healthz"
  status = 301

# ────────────────────────────────
# CONTEXTS
# ────────────────────────────────

[context.production.environment]
  NODE_ENV = "production"
  STRIPE_SECRET_KEY = "your_prod_stripe_secret_key"
  SUPABASE_SERVICE_ROLE_KEY = "your_prod_supabase_service_key"

[context.staging.environment]
  NODE_ENV = "staging"
  API_URL = "https://staging-api.yourdomain.com"
  STRIPE_SECRET_KEY = "your_staging_stripe_secret_key"
  SUPABASE_SERVICE_ROLE_KEY = "your_staging_supabase_service_key"

[context.development.environment]
  NODE_ENV = "development"
  API_URL = "http://localhost:3000/api"
  SUPABASE_URL = "http://localhost:54321"
  STRIPE_SECRET_KEY = "your_dev_stripe_secret_key"
  SUPABASE_SERVICE_ROLE_KEY = "your_dev_supabase_service_key"

[context.worker.environment]
  WORKER_MODE = "true"
  WORKER_API_URL = "https://worker-api.yourdomain.com"
