[build]
  command = "npm ci --include=dev && npm run build"
  
  # Skip API route static generation during build

# Use Netlify's Next.js plugin for proper support
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# Headers are configured in next.config.js


# Node.js version specification
[build.environment]
  NODE_VERSION = "20.17.0"

# Environment variable handling
[context.production.environment]
  NODE_ENV = "production"
  BUILDING = "true"
  NETLIFY = "true"
  # Stripe environment variables will be set in Netlify dashboard

[context.deploy-preview.environment]
  NODE_ENV = "development"
  BUILDING = "true"
  NETLIFY = "true"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  BUILDING = "true"
  NETLIFY = "true"