[build]
  command = "npm run build"
  publish = ".next"
  # Ignore Netlify functions - we use Next.js API routes instead
  functions = ""

[build.environment]
  NODE_VERSION = "18.20.0"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirects for API routes
[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

# Health check redirects
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/healthz"
  status = 200