[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.0"


# Function settings - using array format only
[[functions]]
  node_bundler = "esbuild"

# Background function configuration (15-minute timeout for job processing)
[[functions]]
  name = "process-job-background"
  timeout = 900
  max_age = 86400

# Standard function configuration (5-minute timeout)
[[functions]]
  pattern = "*"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirects for API routes
[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

# Health check redirects
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/healthz"
  status = 200