# 🚀 TAYLOR'S NETLIFY CONFIGURATION - Bulletproof deployment settings
# Optimized for Next.js 14 with enterprise-grade performance

[build]
  # Build command for Next.js static export
  command = "npm run build && npm run export"
  
  # Output directory for static files
  publish = "out"
  
  # Environment variables for build
  environment = { NODE_ENV = "production", NETLIFY = "true" }

[build.processing]
  # Skip processing of these file types for faster builds
  skip_processing = false

[build.processing.css]
  # Let Next.js handle CSS optimization
  bundle = false
  minify = false

[build.processing.js]
  # Let Next.js handle JS optimization
  bundle = false
  minify = false

[build.processing.html]
  # Minimal HTML processing
  pretty_urls = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static assets aggressively
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes would go to Netlify Functions (if using them)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

# SPA fallback for client-side routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  force = false

# Redirect www to non-www
[[redirects]]
  from = "https://www.directorybolt.com/*"
  to = "https://directorybolt.com/:splat"
  status = 301
  force = true

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Build plugins for optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables (set in Netlify dashboard)
# NODE_ENV = "production"
# NEXT_PUBLIC_SITE_URL = "https://directorybolt.com"
# NETLIFY = "true"