[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[functions]]
  name = "process-job-background"
  timeout = 900
  node_bundler = "esbuild"
  external_node_modules = [
    "playwright",
    "playwright-chromium",
    "@supabase/supabase-js",
    "canvas",
    "sharp"
  ]
  included_files = [
    "worker/**",
    "netlify/functions/**"
  ]

[functions."*"]
  timeout = 300

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/customer-validate"
  to = "/.netlify/functions/customer-validate"
  status = 200

[[redirects]]
  from = "/api/jobs-update"
  to = "/.netlify/functions/jobs-update"
  status = 200

[[redirects]]
  from = "/api/jobs-next"
  to = "/.netlify/functions/jobs-next"
  status = 200

[[redirects]]
  from = "/api/jobs-retry"
  to = "/.netlify/functions/jobs-retry"
  status = 200

[[redirects]]
  from = "/api/jobs-complete"
  to = "/.netlify/functions/jobs-complete"
  status = 200

[[redirects]]
  from = "/api/health-supabase"
  to = "/.netlify/functions/health-supabase"
  status = 200

[[redirects]]
  from = "/api/healthz"
  to = "/.netlify/functions/healthz"
  status = 200

[[redirects]]
  from = "/api/version"
  to = "/.netlify/functions/version"
  status = 200