[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[functions]]
  name = "process-job-background"
  timeout = 900
  node_bundler = "esbuild"
  external_node_modules = ["playwright", "playwright-chromium", "@supabase/supabase-js", "canvas", "sharp"]
  included_files = ["worker/**", "netlify/functions/**"]

[functions."*"]
  timeout = 300

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200
