services:
  - type: web
    name: playwright-worker
    runtime: docker
    dockerfilePath: ./workers/playwright-worker/Dockerfile
    dockerContext: ./
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: POLL_INTERVAL
        value: 5000
      - key: PORT
        value: 3000
      - key: API_BASE_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false

