[phases.setup]
nixPkgs = ['nodejs', 'playwright-driver', 'chromium']

[phases.install]
cmds = [
  'npm ci --no-audit --no-fund',
  'npx playwright install chromium --with-deps'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node dist/index.js'
