[phases.setup]
nixPkgs = ['nodejs', 'playwright-driver', 'chromium']

[phases.install]
cmds = [
  'npm ci --no-audit --no-fund',
  'npx playwright install chromium --with-deps'
]

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'node custom-poller.js'
