[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.airtable.com;"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "chrome-extension://*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Extension-ID"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health-check"
  status = 200

[[redirects]]
  from = "/api/user/*"
  to = "/.netlify/functions/user-management/:splat"
  status = 200

[[redirects]]
  from = "/api/analytics/*"
  to = "/.netlify/functions/analytics-collector/:splat"
  status = 200

[[redirects]]
  from = "/api/directories/*"
  to = "/.netlify/functions/directory-manager/:splat"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas"]
  included_files = ["data/**"]

[[plugins]]
  package = "@netlify/plugin-sitemap"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }