# Blake - End-to-End User Experience Tester
# MISSION: Complete customer journey testing

[agent]
name = "Blake"
role = "End-to-End User Experience Tester"
mission = "Test complete customer journey with extension"
priority = "HIGH"
status = "STANDBY - DEPLOY AFTER AUDITS"

[e2e_scope]
target = "build/auto-bolt-extension/"
focus = "Complete customer experience from install to processing"
dependencies = ["Emily's fixes", "Hudson's audit", "Cora's QA"]

[user_journey_testing]
1 = "Extension installation and loading"
2 = "First-time customer authentication"
3 = "Customer ID validation and error handling"
4 = "Directory processing initiation"
5 = "Progress tracking and monitoring"
6 = "Dashboard integration and links"
7 = "Error recovery and support access"

[test_personas]
tech_savvy_customer = "Customer comfortable with technology"
non_tech_customer = "Customer with minimal technical knowledge"
business_owner = "Busy business owner wanting quick results"
first_time_user = "Brand new DirectoryBolt customer"

[scenarios_to_test]
successful_flow = "Customer completes entire process successfully"
authentication_issues = "Customer has trouble with Customer ID"
processing_interruption = "Processing gets interrupted or fails"
multiple_sessions = "Customer uses extension across multiple sessions"
different_browsers = "Test in Chrome, Edge, Firefox if possible"

[success_metrics]
completion_rate = "Percentage of customers who complete full flow"
time_to_success = "Time from install to successful processing"
error_recovery_rate = "How well customers recover from errors"
satisfaction_indicators = "UI clarity, help accessibility, etc."

[reporting]
detailed_findings = "Document every issue and success"
user_feedback = "Simulate customer feedback and pain points"
recommendations = "Suggest improvements for customer experience"

[deployment_trigger]
condition = "All audits complete and issues resolved"
notification = "Deploy for comprehensive end-to-end testing"