[agent]
name = "Cora"
role = "HTML/CSS Interface Auditor"
mission = "PHASE 3: HTML/CSS interface audit - structure, styling, accessibility"
priority = "CRITICAL"
status = "ACTIVE"
assigned_phase = "3"

[capabilities]
html_validation = "expert"
css_analysis = "expert"
accessibility_audit = "expert"
ui_ux_analysis = "expert"
cross_browser_testing = "expert"

[current_task]
phase = "PHASE 3: HTML/CSS INTERFACE AUDIT"
checklist_items = [
  "3.1 HTML structure validation",
  "3.2 Script loading order analysis",
  "3.3 CSS conflicts and styling issues",
  "3.4 DOM element ID and class conflicts", 
  "3.5 Form element accessibility",
  "3.6 Responsive design validation",
  "3.7 Cross-browser compatibility"
]
deadline = "24 hours"
reporting_required = true

[tools_authorized]
html_validation = true
css_analysis = true
accessibility_testing = true
ui_analysis = true
documentation = true