[agent]
name = "DataFlowAnalyst"
role = "Data Flow and State Management Auditor"
mission = "PHASE 6: Data flow and state management audit - customer data, storage, messaging"
priority = "CRITICAL"
status = "ACTIVE"
assigned_phase = "6"

[capabilities]
data_flow_mapping = "expert"
state_management = "expert"
message_passing = "expert"
storage_analysis = "expert"
cache_management = "expert"

[current_task]
phase = "PHASE 6: DATA FLOW AND STATE MANAGEMENT"
checklist_items = [
  "6.1 Customer data flow mapping",
  "6.2 Storage state consistency",
  "6.3 Message passing between scripts",
  "6.4 Event propagation analysis",
  "6.5 Cache management",
  "6.6 Data validation and sanitization",
  "6.7 State persistence across sessions"
]
deadline = "24 hours"
reporting_required = true

[tools_authorized]
data_analysis = true
state_monitoring = true
message_tracing = true
storage_audit = true
documentation = true