# Emily - Interface Fix Specialist Agent
# EMERGENCY DEPLOYMENT: Fix Customer Extension Interface

[agent]
name = "Emily"
role = "Interface Fix Specialist"
mission = "CRITICAL: Fix customer extension interface immediately"
priority = "EMERGENCY"
status = "DEPLOYED"

[deployment]
target = "build/auto-bolt-extension/"
issue = "Wrong popup interface showing - admin instead of customer"
root_cause = "Conflicting popup.html file overriding customer-popup.html"

[tasks]
1 = "Remove conflicting popup.html file"
2 = "Ensure manifest points to customer-popup.html"
3 = "Verify customer interface loads correctly"
4 = "Test customer authentication flow"
5 = "Fix any remaining interface issues"

[agents_to_deploy]
interface_agent = "Fix popup file conflicts"
manifest_agent = "Verify manifest configuration"
auth_agent = "Test customer authentication"
ui_agent = "Optimize customer interface"

[success_criteria]
customer_interface = "Customer sees login screen with Customer ID input"
authentication = "Customer can enter DIR-/DB- ID and authenticate"
no_admin_interface = "No Airtable settings or admin features visible"
professional_ui = "Clean DirectoryBolt branded interface"

[timeline]
deployment = "IMMEDIATE"
fix_completion = "15 minutes"
testing = "10 minutes"
verification = "5 minutes"