# Railway.app Deployment Configuration for DirectoryBolt AutoBolt Workers
# Deploy with: railway up

# Project Configuration
name: directorybolt-autobolt-workers
description: "DirectoryBolt AutoBolt Worker Service - Playwright-based form automation with enterprise scaling"

# Services Configuration
services:
  # Primary Worker Service
  worker:
    build:
      dockerfile: deployment/Dockerfile
      context: ./
    environment:
      NODE_ENV: production
      TWO_CAPTCHA_KEY: "${TWO_CAPTCHA_KEY}"
      ORCHESTRATOR_URL: "https://directorybolt.netlify.app/api"
      WORKER_AUTH_TOKEN: $WORKER_AUTH_TOKEN
      HTTP_PROXY_ENABLED: "true"
      HTTP_PROXY_SERVER: $HTTP_PROXY_SERVER
      HTTP_PROXY_USERNAME: $HTTP_PROXY_USERNAME
      HTTP_PROXY_PASSWORD: $HTTP_PROXY_PASSWORD
      MAX_JOBS_PER_WORKER: "3"
      WORKER_TIMEOUT: "300000"
      HEADLESS: "true"
      LOG_LEVEL: "info"
      REDIS_URL: $REDIS_URL
    healthcheck:
      path: /health
      port: 3000
      interval: 30
      timeout: 10
      retries: 3
    resources:
      memory: 2048
      cpu: 1000
      disk: 1
    scaling:
      min: 2
      max: 8
      policy:
        metric: cpu
        target: 70

  # Proxy Management Service
  proxy-manager:
    build:
      dockerfile: deployment/Dockerfile.proxy
      context: ./
    environment:
      NODE_ENV: production
      REDIS_URL: $REDIS_URL
      PROXY_LIST: $PROXY_LIST
      PROXY_ROTATION_INTERVAL: "300000"
      PROXY_HEALTH_CHECK_INTERVAL: "60000"
      PROXY_MANAGER_PORT: "3002"
    healthcheck:
      path: /health
      port: 3002
      interval: 60
      timeout: 15
      retries: 3
    resources:
      memory: 512
      cpu: 250
      disk: 1

  # Redis Service
  redis:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    command: redis-server --requirepass $REDIS_PASSWORD
    healthcheck:
      command: redis-cli --no-auth-warning -a $REDIS_PASSWORD ping
      interval: 30
      timeout: 10
      retries: 3
    resources:
      memory: 512
      cpu: 250
      disk: 1
    volumes:
      - redis-data:/data

# Environment Variables (set in Railway dashboard)
# WORKER_AUTH_TOKEN - Secure token for worker authentication
# HTTP_PROXY_SERVER - Primary HTTP proxy server URL
# HTTP_PROXY_USERNAME - Proxy authentication username
# HTTP_PROXY_PASSWORD - Proxy authentication password
# PROXY_LIST - Comma-separated list of proxy servers for rotation
# REDIS_PASSWORD - Secure Redis password
# REDIS_URL - Redis connection URL (auto-generated by Railway)

# Volumes
volumes:
  redis-data:
    driver: local

# Network Configuration
network:
  internal: true

# Deployment Configuration
deployment:
  strategy: rolling
  max_unavailable: 1
  health_check:
    grace_period: 30
    interval: 10
    timeout: 5
    unhealthy_threshold: 3
    healthy_threshold: 2

# Monitoring & Observability
observability:
  logs:
    retention: 7d
    level: info
  metrics:
    enabled: true
    endpoint: /metrics
  traces:
    enabled: false
